### ISSUE TITLE
[FE] 호스트 페이지 API 연동

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#106]
## TODO

- [x] 차량 상세 조회 API 연결
- [x] 내 차 예약 내역 API 연결
- [x] 차량 수정 API 연결
- [x] 차량 삭제 API 연결
- [x] 예약 상태 변경 api
- [x] 등록된 차량이 없을때 Redirect

## 설명

- 차량 상세 조회 API 연결
- 내 차 예약 내역 API 연결
- 차량 수정 API 연결
  - reload
- 차량 삭제 API 연결
  - reload
