### ISSUE TITLE
[BE] 회원가입 api 검증 로직 추가

### ISSUE THREAD

**Issue by kelly1422** [softeerbootcamp-3rd/Team9-HexaCore#109]
## TODO

- [ ] 회원가입시에 이메일 형식 인증 추가
- [ ] 비밀번호 형식 인증
- [ ] 전화번호 형식 인증

## 설명

- 클라이언트에서만 입력 값 형식 체크하도록 했는데,
- 서버에서도 검사해줍니다.
