### ISSUE TITLE
[FE] 프론트엔드 배포 파이프라인 구축

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#111]
## TODO

- [x] gihhub action으로 리액트 build하기
- [x] ssh로 ec2에 빌드 파일 복사하기
- [x] nginx root 경로에 빌드파일 연결하기
- [x] ec2에 도메인 연결하기
- [x] nginx에서 /api/v1/요청 백엔드로 포워딩하기
