### ISSUE TITLE
[FE] 마이페이지 API 연동 

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#127]
## TODO

- [x] 사용자 정보 수정
- [x] 게스트 예약 내역 조회
- [x] 예약 상태 변경 API 연동
- [x] 예약 상태 type 변경
- [x] 로그인 하지 않았을시 에러 페이지 로딩 수정

## 설명

- 사용자 정보 수정
  - 페이지 이동
- 예약 상태 변경
  - list component에 버튼별로 api 다르게 만들기
