### ISSUE TITLE
[BE] DB 더미데이터 쌓기

### ISSUE THREAD

**Issue by SuHyeon00** [softeerbootcamp-3rd/Team9-HexaCore#130]
- #136

## TODO

- [ ] 차량 등록을 위한 유저 정보 300만개 랜덤 생성
- [ ] 각 유저별로 차량을 등록한다 가정하여 차량 데이터 300만개 랜덤 생성
- [ ] 각 차량 별 예약 가능 날짜 구간 랜덤 생성

## 설명

- 차량 정보 생성 시 서울의 인구가 전국 대비 1/6이고, 면적 차지 비율은 1/27인 점을 고려하여 서울에 가중치를 5로 나머지 구역에 가중치를 1로 주어 총 260만개의 데이터는 전국의 위, 경도 범위를 기준으로 랜덤 생성하였고, 40만개의 데이터는 서울의 위, 경도 범위를 기준으로 랜덤 생성함

**Comment by SuHyeon00** [comment]
### user 더미 데이터 코드

```python
import pymysql
import random
from datetime import datetime, timedelta
import string

# 패스워드 생성 함수
def generate_password(length=8):
  characters = string.ascii_letters + string.digits + string.punctuation
  return ''.join(random.choice(characters) for i in range(length))

# 랜덤한 이메일 생성 함수
def generate_random_email():
    domain = "@example.com"
    username_length = 10
    username = ''.join(random.choices(string.ascii_lowercase + string.digits, k=username_length))
    return username + domain

# 데이터베이스 연결 설정
conn = pymysql.connect(host='host', user='user_name', password='password', db='database_name')

try:
  with conn.cursor() as cursor:
    # 300만 건의 데이터를 100,000건씩 묶어서 삽입
      for batch in range(30):  # 300만 / 10만 = 30
        values = []
        for i in range(100000):  # 10만 건의 데이터 생성
          email = generate_random_email()
          password = generate_password()  # 랜덤한 패스워드 생성
          name = f'User {random.randint(1, 1000000)}'
          phone_number = f'010-{random.randint(1000, 9999)}-{random.randint(1000, 9999)}'
          is_deleted = False
          
          # BaseTime에 대한 처리
          created_at = datetime.now()
          updated_at = datetime.now()
                
          values.append((email, password, name, phone_number, is_deleted, created_at, updated_at))

        # Bulk Insert
        query = "INSERT INTO user (email, password, name, phone_number, is_deleted, created_at, updated_at) VALUES (%s, %s, %s, %s, %s, %s, %s)"
        cursor.executemany(query, values)
        conn.commit()
          
        # 진행 상황 출력
        print(f"Batch {batch + 1}/30 inserted successfully.")
finally:
  conn.close()
```

**Comment by SuHyeon00** [comment]
### car 더미 데이터 (30개 loop 중에서 26개만 전국에 뿌리기)

```python
import pymysql
import random
import re
from datetime import datetime

# 전국의 위도 범위 설정
seoul_latitude_min = 35.193871
seoul_latitude_max = 37.7

# 전국의 경도 범위 설정
seoul_longitude_min = 126.713299
seoul_longitude_max = 128.736105

# owner_id 초기값 설정 -> 먼저 돌린 코드에 따라 달라질 수 있음!!!
owner_id = 1

# 차량 번호 생성 함수
def generate_car_number():
  # 한글 자음 모음 리스트
  hangul_characters = [
      "가", "갸", "거", "겨", "고", "교", "구", "규", "그", "기",
      "나", "냐", "너", "녀", "노", "뇨", "누", "뉴", "느", "니",
      "다", "댜", "더", "뎌", "도", "됴", "두", "듀", "드", "디",
      "라", "랴", "러", "려", "로", "료", "루", "류", "르", "리",
      "마", "먀", "머", "며", "모", "묘", "무", "뮤", "므", "미",
      "바", "뱌", "버", "벼", "보", "뵤", "부", "뷰", "브", "비",
      "사", "샤", "서", "셔", "소", "쇼", "수", "슈", "스", "시",
      "아", "야", "어", "여", "오", "요", "우", "유", "으", "이",
      "자", "쟈", "저", "져", "조", "죠", "주", "쥬", "즈", "지",
      "차", "챠", "처", "쳐", "초", "쵸", "추", "츄", "츠", "치",
      "카", "캬", "커", "켜", "코", "쿄", "쿠", "큐", "크", "키",
      "타", "탸", "터", "텨", "토", "퇴", "투", "튜", "트", "티",
      "파", "퍄", "퍼", "펴", "포", "표", "푸", "퓨", "프", "피",
      "하", "햐", "허", "혀", "호", "효", "후", "휴", "흐", "히"
  ]

  # 랜덤한 음절 선택
  random_hangul_syllable = random.choice(hangul_characters)
  
  # '00' 다음에 한 글자의 한글, 네 개의 숫자로 구성되는 패턴
  pattern = re.compile(r'[0-9]{2}[' + random_hangul_syllable + r'][0-9]{4}')
  
  # 패턴에 맞는 차량 번호 생성
  car_number = ''
  while not car_number:
    candidate = f"{random.randint(0, 9)}{random.randint(0, 9)}{random_hangul_syllable}{random.randint(0, 9)}{random.randint(0, 9)}{random.randint(0, 9)}{random.randint(0, 9)}"
    if pattern.fullmatch(candidate):
      car_number = candidate
  return car_number

# 주소 데이터 설정 - 원할시 전국 구 리스트를 뽑을 순 있습니다..
seoul_districts = ["강남구", "강동구", "강북구", "강서구", "관악구", "광진구", "구로구", "금천구", "노원구", "도봉구",
                   "동대문구", "동작구", "마포구", "서대문구", "서초구", "성동구", "성북구", "송파구", "양천구", "영등포구",
                   "용산구", "은평구", "종로구", "중구", "중랑구"]

# 동이름 데이터 설정 - 이하 동일
dong_names = ["청담동", "삼성동", "역삼동", "대치동", "논현동", "도곡동", "개포동", "일원동", "수서동", "압구정동",
              "서초동", "방배동", "잠실동", "신천동", "풍납동", "송파동", "석촌동", "잠실동", "강동동", "성내동"]

# 주소 생성 함수
def generate_address():
  district = random.choice(seoul_districts)
  dong = random.choice(dong_names)
  building_number = random.randint(1, 200)
  return f"{district} {dong} {building_number}"

# 데이터베이스 연결 설정
conn = pymysql.connect(host='host', user='user_name', password='password', db='database_name')

try:
  with conn.cursor() as cursor:
    # 300만 건의 데이터를 100,000건씩 묶어서 삽입
    for batch in range(26):  # 260만 / 10만 = 26
      values = []
      for i in range(100000):  # 10만 건의 데이터 생성
        created_at = datetime.now()
        updated_at = datetime.now()
        address = generate_address()
        capacity = random.randint(1, 10)
        car_number = generate_car_number()
        description = f'Description for Car {random.randint(1, 1000000)}'
        fee_per_hour = random.randint(5, 20) * 1000
        fuel = random.randint(0, 4)
        is_deleted = 0
        mileage = round(random.uniform(5, 15), 2)
        latitude = round(random.uniform(seoul_latitude_min, seoul_latitude_max), 6)  # 전국 위도 범위
        longitude = round(random.uniform(seoul_longitude_min, seoul_longitude_max), 6)  # 전국 경도 범위
        position = f'POINT({latitude} {longitude})'
        car_type = random.randint(0, 8)
        year = random.randint(2014, 2024)
        subcategory_id = random.randint(1, 96)
        
        values.append((created_at, updated_at, address, capacity, car_number, description, fee_per_hour, fuel, is_deleted, mileage, position, car_type, year, owner_id, subcategory_id))

        owner_id += 1

      # Bulk Insert
      query = "INSERT INTO car (created_at, updated_at, address, capacity, car_number, description, fee_per_hour, fuel, is_deleted, mileage, position, type, year, owner_id, subcategory_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, ST_GeomFromText(%s, 4326), %s, %s, %s, %s)"
      cursor.executemany(query, values)
      conn.commit()
      
      # 진행 상황 출력
      print(f"Batch {batch + 1}/26 inserted successfully.")
finally:
  conn.close()
```

**Comment by SuHyeon00** [comment]
### car 더미 데이터 (30개 loop 중에서 4개는 서울에 뿌리기)

```python
import pymysql
import random
import re
from datetime import datetime

# 서울의 위도 범위 설정
seoul_latitude_min = 37.3
seoul_latitude_max = 37.7

# 서울의 경도 범위 설정
seoul_longitude_min = 126.8
seoul_longitude_max = 127.2

# owner_id 초기값 설정 -> 먼저 돌린 코드에 따라 달라질 수 있음!!!
owner_id = 1

# 차량 번호 생성 함수
def generate_car_number():
  # 한글 자음 모음 리스트
  hangul_characters = [
      "가", "갸", "거", "겨", "고", "교", "구", "규", "그", "기",
      "나", "냐", "너", "녀", "노", "뇨", "누", "뉴", "느", "니",
      "다", "댜", "더", "뎌", "도", "됴", "두", "듀", "드", "디",
      "라", "랴", "러", "려", "로", "료", "루", "류", "르", "리",
      "마", "먀", "머", "며", "모", "묘", "무", "뮤", "므", "미",
      "바", "뱌", "버", "벼", "보", "뵤", "부", "뷰", "브", "비",
      "사", "샤", "서", "셔", "소", "쇼", "수", "슈", "스", "시",
      "아", "야", "어", "여", "오", "요", "우", "유", "으", "이",
      "자", "쟈", "저", "져", "조", "죠", "주", "쥬", "즈", "지",
      "차", "챠", "처", "쳐", "초", "쵸", "추", "츄", "츠", "치",
      "카", "캬", "커", "켜", "코", "쿄", "쿠", "큐", "크", "키",
      "타", "탸", "터", "텨", "토", "퇴", "투", "튜", "트", "티",
      "파", "퍄", "퍼", "펴", "포", "표", "푸", "퓨", "프", "피",
      "하", "햐", "허", "혀", "호", "효", "후", "휴", "흐", "히"
  ]

  # 랜덤한 음절 선택
  random_hangul_syllable = random.choice(hangul_characters)
  
  # '00' 다음에 한 글자의 한글, 네 개의 숫자로 구성되는 패턴
  pattern = re.compile(r'[0-9]{2}[' + random_hangul_syllable + r'][0-9]{4}')
  
  # 패턴에 맞는 차량 번호 생성
  car_number = ''
  while not car_number:
    candidate = f"{random.randint(0, 9)}{random.randint(0, 9)}{random_hangul_syllable}{random.randint(0, 9)}{random.randint(0, 9)}{random.randint(0, 9)}{random.randint(0, 9)}"
    if pattern.fullmatch(candidate):
      car_number = candidate
  return car_number

# 주소 데이터 설정
seoul_districts = ["강남구", "강동구", "강북구", "강서구", "관악구", "광진구", "구로구", "금천구", "노원구", "도봉구",
                   "동대문구", "동작구", "마포구", "서대문구", "서초구", "성동구", "성북구", "송파구", "양천구", "영등포구",
                   "용산구", "은평구", "종로구", "중구", "중랑구"]

# 동이름 데이터 설정
dong_names = ["청담동", "삼성동", "역삼동", "대치동", "논현동", "도곡동", "개포동", "일원동", "수서동", "압구정동",
              "서초동", "방배동", "잠실동", "신천동", "풍납동", "송파동", "석촌동", "잠실동", "강동동", "성내동"]

# 주소 생성 함수
def generate_address():
  district = random.choice(seoul_districts)
  dong = random.choice(dong_names)
  building_number = random.randint(1, 200)
  return f"{district} {dong} {building_number}"

# 데이터베이스 연결 설정
conn = pymysql.connect(host='host', user='user_name', password='password', db='database_name')

try:
  with conn.cursor() as cursor:
    # 300만 건의 데이터를 100,000건씩 묶어서 삽입
    for batch in range(4):  # 40만 / 10만 = 4
      values = []
      for i in range(100000):  # 10만 건의 데이터 생성
        created_at = datetime.now()
        updated_at = datetime.now()
        address = generate_address()
        capacity = random.randint(1, 10)
        car_number = generate_car_number()
        description = f'Description for Car {random.randint(1, 1000000)}'
        fee_per_hour = random.randint(5, 20) * 1000
        fuel = random.randint(0, 4)
        is_deleted = 0
        mileage = round(random.uniform(5, 15), 2)
        latitude = round(random.uniform(seoul_latitude_min, seoul_latitude_max), 6)  # 서울 위도 범위
        longitude = round(random.uniform(seoul_longitude_min, seoul_longitude_max), 6)  # 서울 경도 범위
        position = f'POINT({latitude} {longitude})'
        car_type = random.randint(0, 8)
        year = random.randint(2014, 2024)
        subcategory_id = random.randint(1, 96)
        
        values.append((created_at, updated_at, address, capacity, car_number, description, fee_per_hour, fuel, is_deleted, mileage, position, car_type, year, owner_id, subcategory_id))

        owner_id += 1

      # Bulk Insert
      query = "INSERT INTO car (created_at, updated_at, address, capacity, car_number, description, fee_per_hour, fuel, is_deleted, mileage, position, type, year, owner_id, subcategory_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, ST_GeomFromText(%s, 4326), %s, %s, %s, %s)"
      cursor.executemany(query, values)
      conn.commit()
      
      # 진행 상황 출력
      print(f"Batch {batch + 1}/4 inserted successfully.")
finally:
  conn.close()
```

**Comment by SuHyeon00** [comment]
### 예약 가능 구간 & 예약 더미 데이터

```python
import pymysql
import random
from datetime import datetime, timedelta

# 데이터베이스 연결 설정
conn = pymysql.connect(host='localhost', user='root', password='', db='tayo_database')

# 랜덤한 날짜 선택 함수
def select_random_dates():
  # 5개의 서로 다른 날짜 랜덤 선택
  dates = [datetime.now() + timedelta(days=random.randint(1, 365)) for _ in range(8)]
  dates.sort()  # 오름차순 정렬
  return dates

# car_id, host_id, car_date_range_id 초기값 설정
car_id = 1
host_id = 1
car_date_range_id = 1

try:
  with conn.cursor() as cursor:
    # 300만 건의 데이터를 100,000건씩 묶어서 삽입
    for batch in range(30):  # 300만 / 10만 = 30
      values = []
      reservations = []
      for i in range(100000):  # 10만 건의 데이터 생성

        # 8개의 서로 다른 날짜 랜덤 선택
        dates = select_random_dates()

        # 첫 번째 record의 start_date와 end_date 설정
        start_date_1, end_date_1 = dates[0], dates[1]

        # 두 번째 record의 start_date와 end_date 설정
        start_date_2, end_date_2 = dates[3], dates[4]

        # 세 번째 record의 start_date와 end_date 설정
        start_date_3, end_date_3 = dates[6], dates[7]

        values.append((start_date_1, end_date_1, car_id))
        values.append((start_date_2, end_date_2, car_id))
        values.append((start_date_3, end_date_3, car_id))

        # 가격 설정
        fee = random.randint(5, 100) * 1000

        # 첫 번째 record에 들어가는 새로운 시작일과 종료일 생성
        new_start_date = start_date_1 + timedelta(days=random.randint(0, (end_date_1 - start_date_1).days))
        new_end_date = end_date_1 + timedelta(days=random.randint(0, (end_date_1 - new_start_date).days))

        status = random.randint(0, 3)
        guest_id = random.randint(1, 3000000)
        
        created_at = datetime.now()
        updated_at = datetime.now()

        reservations.append((created_at, updated_at, fee, new_start_date, new_end_date, status, car_date_range_id, guest_id, host_id))

        car_id += 1
        host_id += 1
        car_date_range_id += 3

      # Bulk Insert 1
      query1 = "INSERT INTO car_date_range (start_date, end_date, car_id) VALUES (%s, %s, %s)"
      print(values)
      cursor.executemany(query1, values)
      query2 = "INSERT INTO reservation (created_at, updated_at, fee, rent_date_time, return_date_time, status, car_date_range_id, guest_id, host_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
      cursor.executemany(query2, reservations)
      conn.commit()

      # 진행 상황 출력
      print(f"Batch {batch + 1}/30 inserted successfully.")
finally:
    conn.close()
```
