### ISSUE TITLE
[BE] reservation, car_date_range 테이블 수정에 따른 더미 데이터 생성하기

### ISSUE THREAD

**Issue by SuHyeon00** [softeerbootcamp-3rd/Team9-HexaCore#136]
## TODO

- [x] car_date_range 더미데이터 쌓기
- [x] reservation 더미데이터 쌓기
- [x] car_image 더미데이터 쌓기

### 기존 더미데이터 코드
- #130 

### 수정 사항
- 기존에 작성된 더미 데이터 생성 코드의 경우 reservation 테이블과 car_date_range 테이블이 연관관계를 맺고 있는 이전 ERD를 반영하고 있어 이를 수정된 ERD에 맞추어 데이터를 생성하는 코드로 수정할 예정입니다.
- 기존 코드에서는 차량 정보를 생성할 때 이미지 정보는 추가하지 않고 있어 각 차량 별 이미지 5개가 추가되도록 해당 부분을 수정할 예정입니다.

**Comment by SuHyeon00** [comment]
### car_date_range & reservation 더미데이터
```python
import pymysql
import random
from datetime import datetime, timedelta

# 데이터베이스 연결 설정
conn = pymysql.connect(host='localhost', user='root', password='', db='tayo_database')

# 랜덤한 날짜 선택 함수
def select_random_dates():
  # 8개의 서로 다른 날짜 랜덤 선택
  dates = [datetime.now() + timedelta(days=random.randint(1, 365)) for _ in range(8)]
  dates.sort()  # 오름차순 정렬
  return dates

# car_id, host_id 초기값 설정
car_id = 1
host_id = 1

try:
  with conn.cursor() as cursor:
    # 300만 건의 데이터를 100,000건씩 묶어서 삽입
    for batch in range(30):  # 300만 / 10만 = 30
      dateRanges = []
      reservations = []
      for i in range(100000):  # 10만 건의 데이터 생성

        # 8개의 서로 다른 날짜 랜덤 선택
        dates = select_random_dates()

        # 첫 번째 record의 start_date와 end_date 설정
        start_date_1, end_date_1 = dates[0], dates[1]

        # 두 번째 record의 start_date와 end_date 설정
        start_date_2, end_date_2 = dates[3], dates[4]

        # 세 번째 record의 start_date와 end_date 설정
        start_date_3, end_date_3 = dates[6], dates[7]

        dateRanges.append((start_date_1, end_date_1, car_id))
        dateRanges.append((start_date_2, end_date_2, car_id))
        dateRanges.append((start_date_3, end_date_3, car_id))

        # 가격 설정
        fee = random.randint(10, 2000) * 1000

        # 예약 가능 구간에 들어가는 새로운 시작일과 종료일 생성
        dates = [[start_date_1, end_date_1], [start_date_2, end_date_2], [start_date_3, end_date_3]]
        offset = random.randint(0, 2)

        start_date = dates[offset][0]
        end_date = dates[offset][1]

        new_start_date = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
        new_end_date = new_start_date + timedelta(days=random.randint(0, (end_date - new_start_date).days))

        status = random.randint(0, 3)
        guest_id = random.randint(1, 3000000)
        
        created_at = datetime.now()
        updated_at = datetime.now()

        reservations.append((created_at, updated_at, fee, new_start_date, new_end_date, status, guest_id, host_id, car_id))

        car_id += 1
        host_id += 1

      # Bulk Insert 1
      query1 = "INSERT INTO car_date_range (start_date, end_date, car_id) VALUES (%s, %s, %s)"
      cursor.executemany(query1, dateRanges)
      query2 = "INSERT INTO reservation (created_at, updated_at, fee, rent_date_time, return_date_time, status, guest_id, host_id, car_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
      cursor.executemany(query2, reservations)
      conn.commit()

      # 진행 상황 출력
      print(f"Batch {batch + 1}/30 inserted successfully.")
finally:
    conn.close()

```

**Comment by SuHyeon00** [comment]
### car_image 더미데이터
```python
import pymysql
import random
from datetime import datetime

# 데이터베이스 연결 설정
conn = pymysql.connect(host='localhost', user='root', password='', db='tayo_database')

# 차량 아이디
car_id = 1

image_urls = [
  "https://hexacore-bucket.s3.ap-northeast-2.amazonaws.com/car3.jpg",
  "https://hexacore-bucket.s3.ap-northeast-2.amazonaws.com/car1.jpg",
  "https://hexacore-bucket.s3.ap-northeast-2.amazonaws.com/car-inside.jpg",
  "https://hexacore-bucket.s3.ap-northeast-2.amazonaws.com/car-detail-front.jpg",
  "https://hexacore-bucket.s3.ap-northeast-2.amazonaws.com/car-side.jpg"
]

try:
  with conn.cursor() as cursor:
    # 300만 건의 데이터를 100,000건씩 묶어서 삽입
      for batch in range(30):  # 300만 / 10만 = 30
        values = []
        for i in range(100000): 
          # 이미지 랜덤하게 섞기
          random.shuffle(image_urls)
          
          # BaseTime에 대한 처리
          created_at = datetime.now()
          updated_at = datetime.now()

          for order in range(5):
            values.append((car_id, image_urls[order], order, created_at, updated_at))

          car_id += 1

        # Bulk Insert
        query = "INSERT INTO car_image (car_id, url, order_idx, created_at, updated_at) VALUES (%s, %s, %s, %s, %s)"
        cursor.executemany(query, values)
        conn.commit()
          
        # 진행 상황 출력
        print(f"Batch {batch + 1}/30 inserted successfully.")
finally:
  conn.close()

```

**Comment by SuHyeon00** [comment]
## 차량 상세 정보 페이지 테스트
### carId 35에 해당하는 예약 가능 날짜 테이블
<img width="537" alt="스크린샷 2024-02-17 오후 4 29 50" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/90602694/8551ac13-f17f-4302-a7c8-eb40edba8d9b">

### carId 35에 해당하는 예약 테이블
<img width="746" alt="스크린샷 2024-02-17 오후 4 31 12" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/90602694/76dfc327-494d-4735-9cfe-2139e4b5ded6">

### 예약 플로우 예시 영상
https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/90602694/b789237c-da88-48d7-9859-caf4e5a3ef94
