### ISSUE TITLE
[BE] 차량 예약 관련 API

### ISSUE THREAD

**Issue by timido7021** [softeerbootcamp-3rd/Team9-HexaCore#14]
## TODO

- [ ] 차량 예약 (`POST /reservations`)
- [ ] 사용자 예약 내역 리스트 조회 (`GET /reservations/guest`)
- [ ] 호스트 예약 내역 리스트 조회 (`GET /reservations/host`)
- [ ] 예약 취소 (`DELETE /reservations/:reservationId`)

## 설명

- 차량 예약 관련 API 4가지를 구현합니다.
- 로그인 상태가 아니거나, 존재하지 않는 예약의 경우 400번대 HTTP 상태코드로 응답합니다.
