### ISSUE TITLE
[FE, BE] 로그아웃, 회원 탈퇴 api 연결 - 회원 탈퇴 api 수정

### ISSUE THREAD

**Issue by kelly1422** [softeerbootcamp-3rd/Team9-HexaCore#147]
## TODO

- [x] 회원가입 페이지 에러메세지 뜨는 위치 수정
- [x] 헤더 로그인 버튼 추가 (로그인하면 로그아웃으로 바뀌게)
- [x] 로그아웃, 회원탈퇴 api 마이페이지에서 연결
- [x] 회원탈퇴 로직 수정 (양방향 매핑 제거)
- [x] 로그인시 유저 아이디 로컬 스토리지에 저장하도록
- [x] 회원탈퇴 했던 사용자가 다시 회원가입을 시도한 경우를 고려해 회원가입 api 수정

## 설명
<img width="501" alt="스크린샷 2024-02-17 오후 9 12 09" src="https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/80809782/fd7f6291-d8b5-47dd-bd0c-79bc2f91d6b9">

회원가입 시에 서버에서 타입 검사 후 보내는 에러메세지는 통합으로 이메일칸에 뜨도록 해놨는데,,,
서버에서 체크한 형식에 대한 에러는 맨 아래에 뜨도록 수정 (입력란은 빨갛게 변하지 않고)

로그인 페이지 들어갈 수 있는 버튼을 헤더에 추가하고, 로그인되어 있는 상황이라면 로그아웃 버튼으로 바뀌도록 합니다.
또한 로그인이 안되어있는 상황에서는 로그인 버튼을 hidden 합니다.

마이페이지에 로그아웃, 회원탈퇴 버튼을 만들고 api를 연결합니다.

User, Car 양방향 매핑을 지우기로 결정되어, 회원탈퇴 로직을 수정합니다.
