### ISSUE TITLE
[ FE ] 호스트페이지 개발

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#15]
## TODO

- [x] 페이지 영역 구분하기
- [x] 차량 정보 카드 만들기
- [x] 캘린더 영역 확보하기
- [x] 예약내역 영역 확보하기

## 설명

- 페이지에 각각의 컴포넌트가 들어갈 영역을 구분한다.
- 차량 정보가 들어가는 카드를 구현하고 더미데이터를 추가한다
- 캘린더가 삽입될 영역을 확보한다
- 예약 리스트를 넣을 영역을 확보한다.
