### ISSUE TITLE
[FE] 호스트 페이지 & 게스트 페이지 버그 수정

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#170]
## TODO

- [x] undefined -> null로 변경
- [x] data-buttonArea 삭제하기
- [x] var data -> const data (profileRoutes.tsx)
