### ISSUE TITLE
[FE] 유저정보 수정 API 연결

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#174]
## TODO

- [x] 회원가입 페이지에서 수정일때 user data 받아오기
- [x] 수정일때 수정 API 연결하기
- [x] 수정 완료후 마이페이지로 redirect하기

## 설명

- 현재 회원가입 페이지와 회원정보 수정 페이지를 공유하고 있음
- 로그인 여부에 따라 회원가입/정보수정 으로 분기
