### ISSUE TITLE
[FE] SSE 클라이언트 구현

### ISSUE THREAD

**Issue by kelly1422** [softeerbootcamp-3rd/Team9-HexaCore#213]
## TODO

- [x] 서버에서 받은 SSE를 클라이언트에서 받습니다.
- [x] 받은 알림을 헤더에 실시간으로 업데이트 해줍니다.
- [x] 특정 알림의 X버튼을 누르면 해당 알림은 삭제+읽음 처리됩니다.
