### ISSUE TITLE
[FE] 프론트 홈 화면, 결제 화면 코드 버그 수정 및 리팩토링

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#223]
## TODO

- [x] #202 버그 수정
- [x] pages 내에서 사용하는 컴포넌트 들은 components 폴더에 빼서 정리하기
- [x] window.locaiton.search -> useLocation으로 분리
- [] useToast 색상 커스터마이징 옵션 추가 --> 수현님이 수정해주심
