### ISSUE TITLE
[BE] 예약 관련 사항 수정

### ISSUE THREAD

**Issue by timido7021** [softeerbootcamp-3rd/Team9-HexaCore#225]
## TODO

- [ ] 예약이 완료된 경우(`Using -> Terminated`) 추가 요금 계산 변경 (0~59분 -> 1시간 추가요금)
- [ ] 예약 조회시 1차로는 `Using->Ready->Cancel->Terminated`순으로, 2차로는 대여시간 순으로 정렬
- [ ] 호스트 예약 조회는 페이지네이션을 쓰지않고 전체 내역을 조회하도록 변경

## 설명

- 추가 요금이 1시간 이전에는 0원으로 된 점을 수정 -> 초과할때부터 추가요금
- 예약 조회시 Repository 에서 정렬해서 조회 결과 응답 (페이지네이션 때문에)
- 호스트 예약 조회는 페이지네이션을 쓰지 않아야 한다.
  - 왜냐하면 예약 가능 일자에 "모든" 예약된 일시를 판단하여 FE에서 보여줘야하기 때문이다.
