### ISSUE TITLE
[FE] 홈 화면

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#24]
## TODO

- [x] API 연결
  - [x] 검색 버튼 클릭 시 검색 api 호출
  - [x] 사이드 바 필터링 버튼 클릭 시 검색 api 호출
  - [x] 카테고리 조회 api 호출 (loader)
- [x] 페이지 퍼블리싱
  - [x] Home.tsx: '/' 로 접근했을 때 나오는 홈 화면 페이지 구현
  - [x] SearchBar.tsx: 차량을 검색할 수 있는 서치바
  - [x] Map.tsx: 서치바에서 위치 탭을 클릭하면 네이버 지도 API를 연동해서 위치를 검색하고, 위경도를 반환할 수 있다.
  - [x] SideBar.tsx: 검색 내역에서 필터링을 설정할 수 있는 사이드 바
  - [x] SelectCarType.tsx: 여러 개의 차종을 클릭할 수 있는 버튼 컴포넌트
  - [x] SingleSelect.tsx: 하나의 모델을 선택할 수 있는 Dropdown 컴포넌트
  - [x] MultipleSelect.tsx: 여러 개의 세부 모델을 선택할 수 있는 Dropdown 컴포넌트
  - [x] SearchBar에서 대여일, 반납일 선택 시 캘린더 붙이기

## API 연결 관련 사항
* URL에 상태 정보 저장 -> useNavigate() 사용할 때마다 Loader 가 실행됨 + 뒤로가기로 왔을 때 검색 결과가 보여지려면 Loader에서 api를 실행해야 함 -> 검색 버튼, 필터링 적용 버튼을 클릭하면 useNavigate를 사용해서 QueryString을 URL로 넘겨주고 Loader에서 인자를 파싱하여 fetchSearchCar() 메서드 호출

* 페이지네이션 어떻게?
