### ISSUE TITLE
[FE] UX 개선을 위한 확인 모달과 토스트 메세지 추가

### ISSUE THREAD

**Issue by kelly1422** [softeerbootcamp-3rd/Team9-HexaCore#253]
## TODO

- [x] 알림 전송시 모달
- [x] 회원탈퇴 할 때 확인 모달
- [x] 로그아웃 성공시 토스트
- [x] 로그아웃 실패시 토스트
- [x] 회원탈퇴 실패시 토스트
- [x] 회원탈퇴 성공시 토스트
- [x] 예약 취소, 거절시 확인 모달
- [x] 디자인 수정

## 설명

-  UX를 개선하기 위해 때에 맞는 확인 모달과 토스트 메세지를 띄워줍니다
