### ISSUE TITLE
[FE, BE] Pre-signed URL 적용

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#259]
## TODO

- [x] GET /cars/presigned-urls API 개발: 백엔드에서 pre-signed URL 링크를 내려주는 API
- [x] 프론트의 차량 등록 페이지 수정
- [x] 백엔드의 차량 등록 API 수정
- [x] 백엔드의 차량 수정 API 수정
- [x] search API 결과에서 이미지 URL에 `downscaled_` PREFIX 붙여서 리턴

## 설명

현재 메인 검색 화면에서 이미지의 크기가 너무 커서 렌더링이 오래 걸리는 문제가 있습니다. 해당 문제를 본질적으로 해결하기 위해서는 이미지를 등록할 때 원본 이미지와 다운스케일된 이미지를 각각 저장하고, 메인 검색 결과에서는 다운스케일된 이미지를 가져오도록 해야 합니다.
또한 이미지를 서버에서 직접 s3로 업로드하는 것은 불필요한 네트워크 부하를 가져오기 때문에 프론트에서 Pre-signed URL을 사용해서 s3에 이미지를 직접 업로드하고 백엔드에는 url만 전달하는 방식으로의 수정이 필요합니다.
