### ISSUE TITLE
[FE] 차량 상세 정보 조회 페이지 구현

### ISSUE THREAD

**Issue by SuHyeon00** [softeerbootcamp-3rd/Team9-HexaCore#26]
## TODO

- [ ] 차량 이미지 보여주는 섹션 구현
- [ ] 차량 상세 정보 보여주는 섹션 구현
- [ ] 시간 선택 섹션 구현
- [ ] 예약하기 섹션 구현

## 사진
![CarDetail](https://github.com/softeerbootcamp-3rd/Team9-HexaCore/assets/90602694/7995aa6f-8514-4012-84b2-98349b65ba02)
