### ISSUE TITLE
[BE] 차량 삭제, 등록 및 세부 모델 조회 API

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#36]
## TODO

- [x] DELETE `/cars/:carId`: 내가 등록한 차량 삭제
- [x] POST `/cars`: 차량 등록
- [x] GET `/cars/categories`: 차량 세부 모델 가져오기
