### ISSUE TITLE
[BE] 차량 등록, 삭제, 세부 모델 조회 API - 테스트 코드 작성

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#61]
## TODO

- [ ] 차량 세부 모델 조회 API 테스트 코드 작성
- [ ] 차량 등록 API 테스트 코드 작성
- [ ] 차량 삭제 API 테스트 코드 작성

## 설명
- BDD 형식 (given - when - then)을 사용한 테스트 코드 작성
