### ISSUE TITLE
[BE] 예약 가능 날짜 수정 api 테스트코드 작성

### ISSUE THREAD

**Issue by SuHyeon00** [softeerbootcamp-3rd/Team9-HexaCore#62]
## TODO

- [ ] 차량 예약 가능 날짜 수정이 데이터베이스에 잘 반영되는지 확인
- [ ] 예약 가능 날짜 구간이 [시작, 끝] 형태가 아닌 경우 에러메시지를 반환하는지 확인
- [ ] 차량 ID에 해당하는 차량 정보가 존재하지 않을 경우 에러 메시지를 반환하는지 확인
