### ISSUE TITLE
[BE] DB 구조 수정하기 & dto 이름 변경하기

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#78]
## TODO

- [x] 모델 ERD 수정
- [ ] 모델 테이블 db 반영
- [x] 모델 데이터 다시 추가

## 설명

- 모델을 상위 모델과 하위 모델로 나누자
- 바뀐 DB 구조에 맞게 데이터를 초기화 하자
