### ISSUE TITLE
[FE] Ajax 요청 통합 처리 함수 제작

### ISSUE THREAD

**Issue by thecloer** [softeerbootcamp-3rd/Team9-HexaCore#82]
## TODO

- [x] 모든 ajax 요청을 처리할 함수 제작
- [x] 유효하지 않은 토큰 일 경우 로그인으로 리다이렉트
- [ ] 만료된 토큰 일 경우 refresh 토큰으로 access 재발급 후 재요청
