### ISSUE TITLE
[BE] 차량 등록, 삭제, 카테고리 조회 API 수정

### ISSUE THREAD

**Issue by Yoon-Suji** [softeerbootcamp-3rd/Team9-HexaCore#88]
## TODO

- [x] 차량 등록 API
- [ ] 차량 삭제 API
- [x] 세부 모델명 조회 API
- [x] 세부 모델명 조회 시 categoryId, subcategoryId 전달해줘야 함

## 설명

차량 등록, 차량 삭제, 세부 모델명 조회 API 수정 및 리팩토링

**Comment by Yoon-Suji** [comment]
DB 구조 재변경에 따라 삭제 API 수정은 #138 이슈로 이동
