### ISSUE TITLE
[BE] 차량 예약 관련 API 변경사항 적용 및 테스트 코드 작성

### ISSUE THREAD

**Issue by timido7021** [softeerbootcamp-3rd/Team9-HexaCore#89]
## TODO

- [ ] 이전 PR(#70) 코드 리뷰 내용 반영 
- [ ] 데이터 구조의 변경에 따른 로직 수정
- [ ] 테스트 코드 작성

## 설명

- 이전 PR 코드 리뷰 내용을 반영하겠습니다.
- `차 - 이용가능날짜 - 예약`으로의 데이터 구조의 변경으로 인한 예약 API의 로직을 변경하겠습니다.
- Controller, Repository, Service 별로 테스트 코드를 작성하겠습니다.
