### ISSUE TITLE
[BE] 차량 조회 수정 API 리팩토링

### ISSUE THREAD

**Issue by jomulagy** [softeerbootcamp-3rd/Team9-HexaCore#90]
## TODO

- [x] 바뀐 ResponseEntity 적용하기
- [x] 인증 적용하기
- [x] DTO에 validater 추가하기
- [x] 예약 가능 일자 조회 관련 로직 수정 //Todo
- [x] 컨트롤러에 @Valid 어노테이션 추가
- [x] 차량수정시 image 전송 없을때 처리 추가

## 설명

- 버전 업그레이드에 따른 refactoring
- 차량 조회는 whitelist에 추가하기
